### ISSUE TITLE
'Freezing' of ImageJ upon re-run of SLIM Curve...

### ISSUE THREAD

**Issue by etarena** [flimlib/flimlib#26]
In general – depending on how this plugin is run/closed – it does not seem to be able to open again in the same ImageJ session.  In fact, ImageJ freezes completely - needing a 'Force Quit' to shut it down.  So a re-start of ImageJ is needed in order to run SLIM Curve again.

(side note: if SLIM Curve is run and then closed by the user - ImageJ appears to function properly as long as SLIM Curve is not tried to run again -- aka - images can be opened, measured, etc.)

*\* this does NOT occur when an image is opened, no 'Fit Curve', and closed by hitting 'Quit' on UI (however, freezing occurs if this is repeated multiple times in the same session) **

One specific example:  
- If grayscale image window is closed manually and then 'Quit' via UI - see comment below (Console 1) this exception is reported.

**Comment by etarena** [comment]
Console #1

Library not on path Unable to load library 'slim-curve-1.0-SNAPSHOT': dlopen(libslim-curve-1.0-SNAPSHOT.dylib, 9): image not found
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ij.gui.ImageWindow.close(ImageWindow.java:387)
	at ij.gui.StackWindow.close(StackWindow.java:192)
	at loci.slim.GrayScaleImage.close(GrayScaleImage.java:240)
	at loci.slim.SLIMProcessor$1.quit(SLIMProcessor.java:691)
	at loci.slim.ui.UserInterfacePanel$2.actionPerformed(UserInterfacePanel.java:449)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by etarena** [comment]
(Fiji Is Just) ImageJ 2.0.0-rc-34/1.50a; Java 1.8.0_51 [64-bit]; Mac OS X 10.10.5

**Comment by Xanthorapedia** [comment]
The SLIM Curve plugin for ImageJ has been retired in favor of [FLIMJ](https://imagej.net/FLIMJ).
