### ISSUE TITLE
FlimJ run issue

### ISSUE THREAD

**Issue by osoyer** [flimlib/flimlib#43]
Hello,
I'm having difficulty running FlimJ after installing it. Installation was done by adding (ticking) FLIMJ site in the updater panel. I have the "FLIMJ" option under "Analyse" menu, however when I load a test image (test2.std) and start FLIMJ, I get a "exception" error and the FlimJ panel does not come up (as shown on FlimJ info page). The full exception error is copy-pasted below. Also, just to mention, I load the test image "test2.std" via BioFormats. It shows up as a single channel image.

best
orkun

(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_202 [64-bit]; Mac OS X 10.16; 432MB of 8388MB (5%)
 
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
	at org.scijava.command.CommandInfo.createInstance(CommandInfo.java:247)
	at org.scijava.command.CommandModule.instantiateCommand(CommandModule.java:248)
	at org.scijava.command.CommandModule.<init>(CommandModule.java:98)
	at org.scijava.command.CommandInfo.createModule(CommandInfo.java:325)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:167)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:206)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:197)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:182)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:302)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

**Comment by paddyroddy** [comment]
See this on how to fix it: https://duderstadt-lab.github.io/mars-docs/install/
